package utils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public enum NameList {
	Aaron,Abbott,Abel,Abner,Abraham,Adair,Adam,Adolph,Adonis,Alan,Albert,Aldrich,Alexander,Alfred,Alger,Allen,Alston,Alvin,Alvis,Amos,Andre,Andrew,Andy,Angelo,Augus,Ansel,Antony,Antonio,Archer,Archibald,Aries,Arlen,Armand,Armstrong,Arno,Arthur,Arvin,Asa,Atwood,Aubrey,August,Augustine,Avery,Baird,Baldwin,Bard,Barlow,Barnett,Baron,Barret,Barry,Bartholomew,Bart,Barton,Basil,Beacher,Beau,Beck,Ben,Benedict,Benjamin,Bennett,Benson,Berg,Bernard,Bernie,Bert,Berton,Bertram,Bevis,Bill,Bing,Bishop,Blair,Blake,Blithe,Bob,Booth,Borg,Boris,Bowen,Boyce,Boyd,Bradley,Brady,Brandon,Brian,Broderick,Brook,Bruce,Bruno,Buck,Burgess,Burke,Burnell,Burton,Byron,Caesar,Calvin,Carey,Carl,Carr,Carter,Cash,Cecil,Cedric,Chad,Channing,Chapman,Charles,Chasel,Chester,Christ,Christian,Christopher,Clare,Clarence,Clark,Claude,Clement,Cleveland,Cliff,Clyde,Colbert,Colby,Colin,Conrad,Corey,Cornelius,Cornell,Curitis,Cyril,Daniel,Darcy,Darnell,Darren,Dave,David,Dean,Dempsey,Dennis,Derrick,Devin,Dick,Dominic,Don,Donahue,Donald,Douglas,Drew,Duke,Duncan,Dunn,Dwight,Dylan,Earl,Ed,Edgar,Edmund,Edison,Edward,Edwiin,Egbert,Eli,Elijah,Elliot,Ellis,Elmer,Elroy,Elton,Elvis,Emmanuel,Enoch,Eric,Ernest,Eugene,Evan,Everley,Fabian,Felix,Ferdinand,Fitch,Ford,Francis,Frank,Franklin,Frederic,Gabriel,Gale,Gary,Gavin,Gene,Geoffrey,George,Gerald,Gilbert,Giles,Glenn,Godfery,Gordon,Greg,Gregary,Griffith,Grover,Guy,Hale,Haley,Hamiltion,Hardy,Harlan,Harley,Harold,Harry,Harvey,Hayden,Henry,Herbert,Herman,Hilary,Hiram,Hobart,Hogan,Horace,Howar,Hubery,Hugh,Hugo,Humphrey,Hunter,Hyman,
	Ian,Ingemar,Ingram,Ira,Isaac,Isidore,Ivan,Ives,Jack,Jackson,Jacob,James,Jared,Jason,Jay,Jeff,Jeffrey,Jeremy,Jerome,Jerry,Jesse,Jim,John,Jonas,Jonathan,Joseph,Joshua,Julian,Julius,Justin,Keith,Ken,Kennedy,Kenneth,Kent,Kerr,Kerwin,Kevin,Kim,King,Kirk,Kyle,Lambert,Lance,Larry,Lawrence,Leif,Len,Lennon,Leo,Leonard,Leopold,Les,Lester,Levi,Lewis,Lionel,Lou,Louis,Lucien,Luther,Lyndon,Magee,Malcolm,Mandel,Marcus,Marico,Mark,Marlon,Marsh,Marshall,Martin,Marvin,Matt,Matthew,Maurice,Max,Maxwell,Meredith,Merle,Merlin,Michael,Michell,Mick,Mike,Miles,Milo,Monroe,Montague,Moore,Morgan,Mortimer,Morton,Moses,Mr,Murphy,Murray,Myron,Nat,Nathan,Nathaniel,Neil,Nelson,Newman,Nicholas,Nick,Nigel,Noah,Noel,Norman,Norton,Ogden,Oliver,Omar,Orville,Osborn,Oscar,Oswald,Otis,Otto,Owen,Parker,Paddy,Patrick,Paul,Payne,Perry,Pete,Peter,Phil,Philip,Porter,Primo,Quentin,Quincy,Quinn,Quintion,Rachel,Ralap,Randolph,Raymond,Reg,Regan,Reginald,Reuben,Rex,Richard,Robert,Robin,Rock,Rod,Roderick,Rodney,Ron,Ronald,Rory,Roy,Rudolf,Rupert,Ryan,Sam,Sampson,Samuel,Saxon,Scott,Sean,Sebastian,Sid,Sidney,Simon,Solomon,Spencer,Stan,Stanford,Stanley,Steven,Steward,Tab,Taylor,Ted,Ternence,Theobald,Theodore,Thomas,Tiffany,Tim,Toby,Todd,Tom,Tony,Tracy,Troy,Truman,Tyler,Tyrone,Ulysses,Upton,Uriah,Valentine,Verne,Vic,Victor,Vincent,Virgil,Vito,Vivian,Wade,Walker,Walter,Ward,Warner,Wayne,Webb,Webster,Wendell,Werner,Wilbur,Will,William,Willie,Winfred,Winston,Woodrow,Wordsworth,Wright,Xavier,Yale,Yehudi,York,Yves,Zachary,Zebulon,Zero,
	
	Abigail,Ada,Adela,Adelaide,Afra,Agatha,Agnes,Alberta,Alexia,Alice,Alma,Althea,Alva,Amanda,Amelia,Amy,Anastasia,Andrea,Angela,Ann,Anna,Annabelle,Antonia,April,Arabela,Arlene,Astrid,Atalanta,Athena,Audrey,Aurora,Barbara,Beatrice,Belinda,Bella,Belle,Bernice,Bertha,Beryl,Bess,Betsy,Betty,Beulah,Beverly,Blanche,Bblythe,Bonnie,Breenda,Bridget,Camille,Candance,Candice,Cara,Carol,Caroline,Catherine,Cathy,Cecilia,Celeste,Charlotte,Cherry,Cheryl,Chloe,Christine,Claire,Clara,Clementine,Constance,Cora,Coral,Cornelia,Crystal,Cynthia,Daisy,Dale,Dana,Daphne,Darlene,Dawn,Debby,Deborah,Deirdre,Delia,Denise,Diana,Dinah,Dolores,Donna,Dora,Doreen,Doris,Dorothy,Eartha,Eden,Edith,Edwina,Eileen,Elaine,Eleanore,Elizabeth,Ella,Ellen,Elma,Elsa,Elsie,Elva,Elvira,Emily,Emma,Enid,Erica,Erin,Esther,Ethel,Eudora,Eunice,Evangeline,Eve,Evelyn,Faithe,Fanny,Fay,Flora,Florence,Frances,Freda,Frederica,Gabrielle,Gail,Gemma,Genevieve,Georgia,Geraldine,Gill,Giselle,Gladys,Gloria,Grace,Griselda,Gustave,Gwendolyn,Hannah,Harriet,Hazel,Heather,Hedda,Hedy,Helen,Heloise,Hermosa,Hilda,Honey,Hulda,Ida,Ina,Ingrid,Irene,Iris,Irma,Isabel,Ivy,Jacqueline,Jamie,Jane,Janet,Janice,Jean,Jennifer,Jenny,Jessie,Jessica,Jill,Jo,Joa,Joanna,Joanne,Jocelyn,Jodie,Josephine,Joy,Joyce,Judith,Judy,Julia,Julie,Juliet,June,Kama,Karen,Katherine,Kay,Kelly,Kimberley,Kitty,Kristin,Laura,Laurel,Lauren,Lee,Leila,Lena,Leona,Lesley,Letitia,Lilith,Lillian,Linda,Lindsay,Lisa,Liz,Lorraine,Louise,Lucy,Lydia,Lynn,Mabel,Madam,Madeline,Madge,Maggie,Mamie,Mandy,Marcia,Margaret,Marguerite,Maria,Marian,Marina,Marjorie,Martha,Martina,Mary,Maud,
	Maureen,Mavis,Maxine,Mag,May,Megan,Melissa,Meroy,Merry,Michelle,Michaelia,Mignon,Mildred,Mirabelle,Miranda,Miriam,Modesty,Moira,Molly,Mona,Monica,Mrs,Muriel,Myra,Myrna,Nancy,Naomi,Natalie,Natividad,Nelly,Nicola,Nicole,Nina,Nora,Norma,Novia,Nydia,Octavia,Odelette,Odelia,Olga,Olive,Olivia,Ophelia,Pag,Page,Pamela,Pandora,Patricia,Paula,Pearl,Penelope,Penny,Philipppa,Phoebe,Phoenix,Phyllis,Polly,Poppy,Prima,Priscilla,Prudence,Queena,Quintina,Rae,Rebecca,Regina,Renata,Renee,Rita,Riva,Roberta,Rosalind,Rose,Rosemary,Roxanne,Ruby,Ruth,Sabina,Sally,Sabrina,Salome,Samantha,Sandra,Sandy,Sara,Sarah,Sebastiane,Selena,Sharon,Sheila,Sherry,Shirley,Sibyl,Sigrid,Simona,Sophia,Spring,Stacey,Setlla,Stephanie,Susan,Susanna,Susie,Suzanne,Sylvia,Tabitha,Tammy,Teresa,Tess,Thera,Theresa,Tina,Tobey,Trista,Truda,Ula,Una,Ursula,Valentina,Valerie,Vanessa,Venus,Vera,Verna,Veromca,Veronica,Victoria,Vicky,Viola,Violet,Virginia,Vita,Vivien,Wallis,Wanda,Wendy,Winifred,Winni,Xanthe,Xaviera,Xenia,Yedda,Yetta,Yvette,Yvonne,Zara,Zenobia,Zoe,Zona,Zora;
    
	public static final HashMap<NameList, String> nameList1 = new HashMap<NameList, String>();
	static {
		String gender = "MALE";
		for(NameList name : NameList.values()){
			nameList1.put(name, gender);
			if(name.toString().equals("Zero")) gender = "FEMALE";
		}
	}
	
	public static final HashMap<String, String> nameList2 = new HashMap<String, String>();
	static {
		for(NameList name : NameList.values()){
			nameList2.put(name.toString(), nameList1.get(name));
		}
	}
}
