package xmlconversion;

public class TagTypes {
	public static final String SOURCEFILE ="source_file";
	public static final String TYPE = "TYPE";
	public static final String SUBTYPE = "SUBTYPE";
	public static final String CLASS = "CLASS";
	public static final String VERSION = "VERSION";
	public static final String SOURCE = "SOURCE";
	public static final String URI = "URI";
	public static final String ENT ="entity";
	public static final String ID = "ID";
	public static final String ENTYPE = "entity_type";
	public static final String GENE = "GENERIC";
	public static final String DOCID = "DOCID";
	public static final String ENTMEN = "entity_mention";
	public static final String ENTATTR = "entity_attributes";
	public static final String NAME = "name";
	public static final String EXTENT = "extent";
	public static final String HEAD = "head";
	public static final String CHARSEQ = "charseq";
	public static final String START = "start";
	public static final String END = "end";
	public static final String DOCU ="document";
	public static final String REL = "relation";
	public static final String ARG = "rel_entity_arg";
	public static final String ENTID = "ENTITYID";
	public static final String ARGNUM = "ARGNUM";
	public static final String RELMENS = "relation_mentions";
	public static final String RELMEN = "relation_mention";
	public static final String RELMENARG = "rel_mention_arg";
//	public static final String RELENTITYARG  =  "rel_entity_arg";
	public static final String RELMENTIME = "rel_mention_time";
	public static final String MENID = "MENTIONID";
	public static final String VAL = "VAL";
	public static final String MOD = "MOD";
	public static final String DIR = "DIR";
	//the following is for tags of .sgm
	public static final String DOC ="DOC";
	public static final String DOCNO ="DOCNO";
	public static final String DOCTYPE = "DOCTYPE";
	public static final String TEXT = "TEXT";
	public static final String TURN = "turn";
	//the followins if for tags of stanford parser output
	public static final String SENTENCES ="sentences";
	public static final String SENTENCE ="sentence";
	public static final String SENTENCEID = "id";
	public static final String WORD ="word";
	public static final String POS = "POS";
	public static final String DEPENDENCYBASIC = "basic-dependencies";
	public static final String DEPENDENCYCOLLAPSED = "collapsed-dependencies";
	public static final String DEPENDENCYPROP = "collapsed-ccprocessed-dependencies";
	public static final String DEPENDENCY = "dep";
	public static final String GOVERNOR = "governor";
	public static final String DEPENDENT = "dependent";
	public static final String DEPENDENCYRELATION = "type";
	public static final String TOKENS = "tokens";
	public static final String TOKEN = "token";
	public static final String TOKENID = "id";
	public static final String DEPENDENCYINDEX = "idx";
	public static final String CHARBEGIN = "CharacterOffsetBegin";
	public static final String CHAREND = "CharacterOffsetEnd";
}
